In [7]:
study_hours = np.array([2, 3, 4, 1, 5, 6, 2])
print(study_hours)
print(type(study_hours))

[2 3 4 1 5 6 2]
<class 'numpy.ndarray'>


In [8]:
print(study_hours[0])   # first value -> 2
print(study_hours[3])   # fourth value -> 1
print(study_hours[-1])  # last value -> 2

2
1
2


In [ ]:
print(study_hours[0:3])   # first 3 values -> [2 3 4]
print(study_hours[3:])    # from index 3 to the end -> [1 5 6 2]print(study_hours + 1)      # adds 1 to every value
print(study_hours * 2)      # doubles every value
print(study_hours.sum())    # adds up all values -> total hours
print(study_hours.mean())   # average hours per day
print(study_hours.max())    # highest value
print(study_hours.min())    # lowest value

[2 3 4]
[1 5 6 2]
[ 4  6  8  2 10 12  4]
23
3.2857142857142856
6
1


In [12]:
data = np.array([[2, 65], [3, 70], [4, 75], [5, 85]])
print(data)
print(data.shape)   # (4, 2) -> 4 rows, 2 columns

[[ 2 65]
 [ 3 70]
 [ 4 75]
 [ 5 85]]
(4, 2)


In [5]:
!pip install numpy

In [6]:
import numpy as np